---
- hosts: all
  tasks:
    - name: Install java
      yum:
        name: java
        state: latest
    - name: Install Git Software
      yum:
        name: git
        state: latest
    - name: Removing Older version of Tomcat
      file: path=/usr/local/tomcat state=absent
    - name: Removing Older Version of Tomcat from the Opt Folder  
      file: path=/opt/Tomcat state=absent
    - name: Copying the Tomcat Software
      copy: src=/root/Desktop/apache-tomcat-8.5.59.tar.gz dest=/opt/Tomcat/
    - name: unarchiveing  The Tomcat Software in opt Folder
      unarchive: src=/opt/Tomcat/apache-tomcat-8.5.59.tar.gz dest=/opt copy=no
    - name: Starting the Tomcat Software Service
      command: nohup /opt/apache-tomcat-8.5.59/bin/startup.sh &
